export default {
    strings: ["I'm coding it."],
    stringsElement: null,
    typeSpeed: 60,
    startDelay: 1000,
    backSpeed: 30,
    smartBackspace: true,
    shuffle: false,
    backDelay: 700,
    fadeOut: false,
    fadeOutClass: "typed-fade-out",
    fadeOutDelay: 500,
    loop: false,
    loopCount: Infinity,
    showCursor: true,
    cursorChar: "|",
    autoInsertCss: true,
    attr: null,
    // attr: ""
    bindInputFocusEvents: false,
    contentType: "html", //["html", "null"]
    onBegin: function(self){},
    onComplete: function(self){},
    preStringTyped: function(arrayPos, self){},
    onStringTyped: function(arrayPos, self){},
    onLastStringBackspaced: function(self){},
    onTypingPaused: function(arrayPos, self){},
    onTypingResumed: function(arrayPos, self){},
    onReset: function(self){},
    onStop: function(arrayPos, self){},
    onStart: function(arrayPos, self){},
    onDestroy: function(self){}
};
